#源于mihomo内核衍生应用配置
[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=Emby影视服,https://raw.githubusercontent.com/404-Not-Found-nginx/Mihomo/refs/heads/main/Filters/Emby.list
ruleset=ONE NZ,https://raw.githubusercontent.com/404-Not-Found-nginx/Loon_Egern_Quantumult-X/refs/heads/main/Filter/Loon/OneNZ_WiFi_Calling.list
ruleset=Ultra,https://raw.githubusercontent.com/404-Not-Found-nginx/Loon_Egern_Quantumult-X/refs/heads/main/Filter/Loon/US_WiFi_Calling.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🔮 IP归属地,https://raw.githubusercontent.com/SunsetMkt/anti-ip-attribution/refs/heads/main/generated/quantumultx.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
ruleset=Google Voice,https://raw.githubusercontent.com/404-Not-Found-nginx/Loon_Egern_Quantumult-X/refs/heads/main/Filter/Loon/GoogleVoice.lsr
ruleset=Google Voice,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/GoogleVoice/GoogleVoice.list
ruleset=💬 Ai平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=💬 Ai平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=📢 谷歌,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=📢 谷歌,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=Ⓜ️ 微软,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=Ⓜ️ OneDrive,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=📈 Speedtest by Ookla,https://kelee.one/Tool/Clash/Rule/SpeedtestInternational.yaml
ruleset=📈 测速网,https://kelee.one/Tool/Clash/Rule/SpeedtestChina.yaml
;ruleset=🐟 漏网之鱼,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
;ruleset=🐟 漏网之鱼,[]FINAL
ruleset=闲鱼,https://raw.githubusercontent.com/404-Not-Found-nginx/ClashRules/refs/heads/main/Filters/Xianyu_Goofish.list
;设置规则标志位


;设置分组标志位
custom_proxy_group=Emby影视服`select`(EMBY|日用)`[]🇭🇰 香港节点`[]🇲🇴 澳门节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点
custom_proxy_group=ONE NZ`select`(新西兰|NZ|🇳🇿)`.*
custom_proxy_group=Ultra`select`[]🇺🇸 美国节点`.*
custom_proxy_group=📲 电报消息`select`[]DIRECT`.*
custom_proxy_group=💬 Ai平台`select`[]🇺🇸 美国节点`[]DIRECT`.*
custom_proxy_group=📢 谷歌`select`[]DIRECT`.*
custom_proxy_group=Google Voice`select`[]🇺🇸 美国节点
custom_proxy_group=📹 油管视频`select`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇰🇷 韩国节点`[]🇮🇳 印度节点`[]🇺🇦 乌克兰节点`[]🇷🇺 俄罗斯节点`[]🇹🇷 土耳其节点`[]🇦🇷 阿根廷节点`[]DIRECT`.*
custom_proxy_group=Ⓜ️ 微软`select`[]DIRECT`.*
custom_proxy_group=Ⓜ️ OneDrive`select`[]DIRECT`.*
custom_proxy_group=📺 哔哩哔哩`select`[]DIRECT`.*
custom_proxy_group=🔮 IP归属地`select`.*`[]DIRECT
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🇺🇸 美国节点`.*
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🇺🇸 美国节点`[]🇮🇳 印度节点`[]🇺🇦 乌克兰节点`[]🇷🇺 俄罗斯节点`[]🇹🇷 土耳其节点`[]🇦🇷 阿根廷节点`.*
custom_proxy_group=🌍 国外媒体`select`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇰🇷 韩国节点`[]🇮🇳 印度节点`[]🇺🇦 乌克兰节点`[]🇷🇺 俄罗斯节点`[]🇹🇷 土耳其节点`[]🇦🇷 阿根廷节点`[]DIRECT`.*
custom_proxy_group=闲鱼`select`.*`[]DIRECT
custom_proxy_group=📈 Speedtest by Ookla`select`.*
custom_proxy_group=📈 测速网`select`[]DIRECT`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT`.*
custom_proxy_group=🆎 AdBlock`select`[]REJECT`[]DIRECT
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🇭🇰 香港节点`[]🇲🇴 澳门节点`[]🇹🇼 台湾节点`.*
custom_proxy_group=🎥 奈飞视频`select`[]🎥 奈飞节点`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇰🇷 韩国节点`[]🇮🇳 印度节点`[]🇺🇦 乌克兰节点`[]🇷🇺 俄罗斯节点`[]🇹🇷 土耳其节点`[]🇦🇷 阿根廷节点`[]DIRECT`.*
;custom_proxy_group=🐟 漏网之鱼`select`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇰🇷 韩国节点`[]🇮🇳 印度节点`[]🇺🇦 乌克兰节点`[]🇷🇺 俄罗斯节点`[]🇹🇷 土耳其节点`[]🇦🇷 阿根廷节点`[]DIRECT`.*
custom_proxy_group=🇭🇰 香港节点`url-test`(香港|深港|沪港|港|Hong Kong|HongKong|HKG|(?<![A-Za-z])HK(?![A-Za-z]))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇲🇴 澳门节点`url-test`(澳门|澳門|Macau|Macao|(?<![A-Za-z])(?:MO|MAC)(?![A-Za-z]))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|Japan|Tokyo|Osaka|(?<![A-Za-z])JP(?![A-Za-z]))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇸 美国节点`url-test`^(?!.*(?:亚美尼亚|Armenia|AU|Australia|澳大利亚|RUS|Russia|俄罗斯|塞浦路斯|Cyprus)).*(?:美国|(?<!亚)美(?!尼亚)|(?<![A-Za-z])US(?![A-Za-z])|USA|United States|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|纽约|迈阿密)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇹🇼 台湾节点`url-test`(台湾|台北|台中|新北|彰化|高雄|TW|Taiwan|Taipei|(?<![平电戏月后台])台)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 狮城节点`url-test`(新加坡|坡|狮城|SG|Singapore|(?<![A-Za-z])SG(?![A-Za-z]))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国节点`url-test`(韩国|首尔|韩|韓|Korea|KOR|Seoul|(?<![A-Za-z])KR(?![A-Za-z]))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇮🇳 印度节点`url-test`(🇮🇳|印度(?!尼)|孟买|新德里|(?<!马)德里|India|Mumbai|Delhi|(?<![A-Za-z])(?:IN|IND)(?![A-Za-z]))`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇺🇦 乌克兰节点`url-test`(乌克兰|基辅|哈尔科夫|Ukraine|Kyiv|Kiev|Kharkiv|(?<![A-Za-z])(?:UA|UKR)(?![A-Za-z]))`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇷🇺 俄罗斯节点`url-test`(俄罗斯|莫斯科|圣彼得堡|新西伯利亚|海参崴|符拉迪沃斯托克|Russia|Moscow|Saint Petersburg|(?<![A-Za-z])(?:RU|RUS)(?![A-Za-z]))`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇹🇷 土耳其节点`url-test`(土耳其|伊斯坦布尔|安卡拉|Turkey|Türkiye|Istanbul|Ankara|(?<![A-Za-z])(?:TR|TUR)(?![A-Za-z]))`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇦🇷 阿根廷节点`url-test`(阿根廷|布宜诺斯艾利斯|Argentina|Buenos Aires|(?<![A-Za-z])(?:AR|ARG)(?![A-Za-z]))`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🎥 奈飞节点`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media)
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;下面这个给CFW用的话可以注释掉
;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml
clash_rule_base=https://raw.githubusercontent.com/404-Not-Found-nginx/ClashRules/main/Mixin.ini
;luck
